<a href="https://colab.research.google.com/github/lugasaji/ML-Zoomcamp-2025/blob/main/ML_Zoomcamp_2025_HomeWork_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## __HOMEWORK 1__

_____

In [107]:
import pandas as pd
import numpy as np
import math

### __Q1. Pandas version__

In [3]:
pd.__version__

'2.2.2'

___

### __Getting the data__

In [4]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

___

### __Q2. Records count__

How many records are in the dataset?

In [6]:
len(df)

9704

___

### __Q3. Fuel types__

How many fuel types are presented in the dataset?

In [120]:
len(df.fuel_type.unique())

2

___

### __Q4. Missing values__

How many columns in the dataset have missing values?

In [45]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [44]:
count = 0
for column in df.columns:
    if df[column].isna().sum() > 0 or df[column].isnull().sum() > 0:
        count += 1

print(f"There are {count} columns avec missign values")

There are 4 columns avec missign values


___

### __Q5. Max fuel efficiency__


What's the maximum fuel efficiency of cars from Asia?

In [60]:
max_fuel_efficiency = df[df.origin == 'Asia'].fuel_efficiency_mpg.max()
print(f"The maximun fuel effiency of cars from Asia is {max_fuel_efficiency:0.3f}")

The maximun fuel effiency of cars from Asia is 23.759


___

### __Q6. Median value of horsepower__



1. Find the median value of the horsepower column in the dataset.


In [82]:
median = df.horsepower.median()
print(f"The median is: {median}")

The median is: 149.0


2. Next, calculate the most frequent value of the same horsepower column.


In [83]:
mode = df.horsepower.mode()
print(f"The most frequent value is: {mode[0]}")

df.horsepower.value_counts().sort_values(ascending=False)

The most frequent value is: 152.0


horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [84]:
mode = df.horsepower.mode()[0]
column_fill = df.horsepower.fillna(mode)
column_fill.median()

152.0


4. Now, calculate the median value of horsepower once again.

In [87]:
mode = df.horsepower.mode()[0]
median = df.horsepower.fillna(mode).median()
print(f"The median is: {median}")

The median is: 152.0


Has it changed?

- __Yes, it increased__

___

### __Q7. Sum of weights__

1. Select all the cars from Asia

In [92]:
asia_cars = df[df.origin == 'Asia']
asia_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

2. Select only columns vehicle_weight and model_year

In [98]:
weight_and_model = asia_cars[["vehicle_weight", "model_year"]]
weight_and_model

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

3. Select the first 7 values

In [101]:
cars_7 = weight_and_model.head(7)

4. Get the underlying NumPy array. Let's call it X.


In [105]:
X = cars_7.values

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.


In [108]:
XTX = np.dot(X.T,X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

6. Invert XTX.


In [109]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].


In [113]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.


In [115]:
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([0.01386421, 0.5049067 ])

9. What's the sum of all the elements of the result?

In [117]:
sum_w = w.sum()
print("The sum is: ", sum_w)

The sum is:  0.5187709081074016
